env:
es256:
  privateKey:
  publicKey:
mongoURI:
  test:
  dev:
  prod:
postgresURI:
  test:
  dev:
  prod:
s3:
  bucketNames:
    photos:
      test:
      dev:
      prod:
  credentials:
    id:
    secret:
  endpoint:
  region:
server:
  port:
