// Code generated by entc, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"math"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/baturalpk/photo-bucket/ent/photosmetadata"
	"github.com/baturalpk/photo-bucket/ent/predicate"
	"github.com/baturalpk/photo-bucket/ent/profile"
	"github.com/google/uuid"
)

// PhotosMetadataQuery is the builder for querying PhotosMetadata entities.
type PhotosMetadataQuery struct {
	config
	limit      *int
	offset     *int
	unique     *bool
	order      []OrderFunc
	fields     []string
	predicates []predicate.PhotosMetadata
	// eager-loading edges.
	withOwner *ProfileQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PhotosMetadataQuery builder.
func (pmq *PhotosMetadataQuery) Where(ps ...predicate.PhotosMetadata) *PhotosMetadataQuery {
	pmq.predicates = append(pmq.predicates, ps...)
	return pmq
}

// Limit adds a limit step to the query.
func (pmq *PhotosMetadataQuery) Limit(limit int) *PhotosMetadataQuery {
	pmq.limit = &limit
	return pmq
}

// Offset adds an offset step to the query.
func (pmq *PhotosMetadataQuery) Offset(offset int) *PhotosMetadataQuery {
	pmq.offset = &offset
	return pmq
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (pmq *PhotosMetadataQuery) Unique(unique bool) *PhotosMetadataQuery {
	pmq.unique = &unique
	return pmq
}

// Order adds an order step to the query.
func (pmq *PhotosMetadataQuery) Order(o ...OrderFunc) *PhotosMetadataQuery {
	pmq.order = append(pmq.order, o...)
	return pmq
}

// QueryOwner chains the current query on the "owner" edge.
func (pmq *PhotosMetadataQuery) QueryOwner() *ProfileQuery {
	query := &ProfileQuery{config: pmq.config}
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := pmq.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(photosmetadata.Table, photosmetadata.FieldID, selector),
			sqlgraph.To(profile.Table, profile.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, photosmetadata.OwnerTable, photosmetadata.OwnerColumn),
		)
		fromU = sqlgraph.SetNeighbors(pmq.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PhotosMetadata entity from the query.
// Returns a *NotFoundError when no PhotosMetadata was found.
func (pmq *PhotosMetadataQuery) First(ctx context.Context) (*PhotosMetadata, error) {
	nodes, err := pmq.Limit(1).All(ctx)
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{photosmetadata.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) FirstX(ctx context.Context) *PhotosMetadata {
	node, err := pmq.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PhotosMetadata ID from the query.
// Returns a *NotFoundError when no PhotosMetadata ID was found.
func (pmq *PhotosMetadataQuery) FirstID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(1).IDs(ctx); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{photosmetadata.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) FirstIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PhotosMetadata entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PhotosMetadata entity is found.
// Returns a *NotFoundError when no PhotosMetadata entities are found.
func (pmq *PhotosMetadataQuery) Only(ctx context.Context) (*PhotosMetadata, error) {
	nodes, err := pmq.Limit(2).All(ctx)
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{photosmetadata.Label}
	default:
		return nil, &NotSingularError{photosmetadata.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) OnlyX(ctx context.Context) *PhotosMetadata {
	node, err := pmq.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PhotosMetadata ID in the query.
// Returns a *NotSingularError when more than one PhotosMetadata ID is found.
// Returns a *NotFoundError when no entities are found.
func (pmq *PhotosMetadataQuery) OnlyID(ctx context.Context) (id uuid.UUID, err error) {
	var ids []uuid.UUID
	if ids, err = pmq.Limit(2).IDs(ctx); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = &NotSingularError{photosmetadata.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) OnlyIDX(ctx context.Context) uuid.UUID {
	id, err := pmq.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PhotosMetadataSlice.
func (pmq *PhotosMetadataQuery) All(ctx context.Context) ([]*PhotosMetadata, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return nil, err
	}
	return pmq.sqlAll(ctx)
}

// AllX is like All, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) AllX(ctx context.Context) []*PhotosMetadata {
	nodes, err := pmq.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PhotosMetadata IDs.
func (pmq *PhotosMetadataQuery) IDs(ctx context.Context) ([]uuid.UUID, error) {
	var ids []uuid.UUID
	if err := pmq.Select(photosmetadata.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) IDsX(ctx context.Context) []uuid.UUID {
	ids, err := pmq.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (pmq *PhotosMetadataQuery) Count(ctx context.Context) (int, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return pmq.sqlCount(ctx)
}

// CountX is like Count, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) CountX(ctx context.Context) int {
	count, err := pmq.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (pmq *PhotosMetadataQuery) Exist(ctx context.Context) (bool, error) {
	if err := pmq.prepareQuery(ctx); err != nil {
		return false, err
	}
	return pmq.sqlExist(ctx)
}

// ExistX is like Exist, but panics if an error occurs.
func (pmq *PhotosMetadataQuery) ExistX(ctx context.Context) bool {
	exist, err := pmq.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PhotosMetadataQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (pmq *PhotosMetadataQuery) Clone() *PhotosMetadataQuery {
	if pmq == nil {
		return nil
	}
	return &PhotosMetadataQuery{
		config:     pmq.config,
		limit:      pmq.limit,
		offset:     pmq.offset,
		order:      append([]OrderFunc{}, pmq.order...),
		predicates: append([]predicate.PhotosMetadata{}, pmq.predicates...),
		withOwner:  pmq.withOwner.Clone(),
		// clone intermediate query.
		sql:    pmq.sql.Clone(),
		path:   pmq.path,
		unique: pmq.unique,
	}
}

// WithOwner tells the query-builder to eager-load the nodes that are connected to
// the "owner" edge. The optional arguments are used to configure the query builder of the edge.
func (pmq *PhotosMetadataQuery) WithOwner(opts ...func(*ProfileQuery)) *PhotosMetadataQuery {
	query := &ProfileQuery{config: pmq.config}
	for _, opt := range opts {
		opt(query)
	}
	pmq.withOwner = query
	return pmq
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PhotosMetadata.Query().
//		GroupBy(photosmetadata.FieldOwnerID).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
//
func (pmq *PhotosMetadataQuery) GroupBy(field string, fields ...string) *PhotosMetadataGroupBy {
	group := &PhotosMetadataGroupBy{config: pmq.config}
	group.fields = append([]string{field}, fields...)
	group.path = func(ctx context.Context) (prev *sql.Selector, err error) {
		if err := pmq.prepareQuery(ctx); err != nil {
			return nil, err
		}
		return pmq.sqlQuery(ctx), nil
	}
	return group
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		OwnerID uuid.UUID `json:"owner_id,omitempty"`
//	}
//
//	client.PhotosMetadata.Query().
//		Select(photosmetadata.FieldOwnerID).
//		Scan(ctx, &v)
//
func (pmq *PhotosMetadataQuery) Select(fields ...string) *PhotosMetadataSelect {
	pmq.fields = append(pmq.fields, fields...)
	return &PhotosMetadataSelect{PhotosMetadataQuery: pmq}
}

func (pmq *PhotosMetadataQuery) prepareQuery(ctx context.Context) error {
	for _, f := range pmq.fields {
		if !photosmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if pmq.path != nil {
		prev, err := pmq.path(ctx)
		if err != nil {
			return err
		}
		pmq.sql = prev
	}
	return nil
}

func (pmq *PhotosMetadataQuery) sqlAll(ctx context.Context) ([]*PhotosMetadata, error) {
	var (
		nodes       = []*PhotosMetadata{}
		_spec       = pmq.querySpec()
		loadedTypes = [1]bool{
			pmq.withOwner != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]interface{}, error) {
		node := &PhotosMetadata{config: pmq.config}
		nodes = append(nodes, node)
		return node.scanValues(columns)
	}
	_spec.Assign = func(columns []string, values []interface{}) error {
		if len(nodes) == 0 {
			return fmt.Errorf("ent: Assign called without calling ScanValues")
		}
		node := nodes[len(nodes)-1]
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	if err := sqlgraph.QueryNodes(ctx, pmq.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}

	if query := pmq.withOwner; query != nil {
		ids := make([]uuid.UUID, 0, len(nodes))
		nodeids := make(map[uuid.UUID][]*PhotosMetadata)
		for i := range nodes {
			fk := nodes[i].OwnerID
			if _, ok := nodeids[fk]; !ok {
				ids = append(ids, fk)
			}
			nodeids[fk] = append(nodeids[fk], nodes[i])
		}
		query.Where(profile.IDIn(ids...))
		neighbors, err := query.All(ctx)
		if err != nil {
			return nil, err
		}
		for _, n := range neighbors {
			nodes, ok := nodeids[n.ID]
			if !ok {
				return nil, fmt.Errorf(`unexpected foreign-key "owner_id" returned %v`, n.ID)
			}
			for i := range nodes {
				nodes[i].Edges.Owner = n
			}
		}
	}

	return nodes, nil
}

func (pmq *PhotosMetadataQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := pmq.querySpec()
	_spec.Node.Columns = pmq.fields
	if len(pmq.fields) > 0 {
		_spec.Unique = pmq.unique != nil && *pmq.unique
	}
	return sqlgraph.CountNodes(ctx, pmq.driver, _spec)
}

func (pmq *PhotosMetadataQuery) sqlExist(ctx context.Context) (bool, error) {
	n, err := pmq.sqlCount(ctx)
	if err != nil {
		return false, fmt.Errorf("ent: check existence: %w", err)
	}
	return n > 0, nil
}

func (pmq *PhotosMetadataQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := &sqlgraph.QuerySpec{
		Node: &sqlgraph.NodeSpec{
			Table:   photosmetadata.Table,
			Columns: photosmetadata.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeUUID,
				Column: photosmetadata.FieldID,
			},
		},
		From:   pmq.sql,
		Unique: true,
	}
	if unique := pmq.unique; unique != nil {
		_spec.Unique = *unique
	}
	if fields := pmq.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, photosmetadata.FieldID)
		for i := range fields {
			if fields[i] != photosmetadata.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := pmq.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := pmq.limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := pmq.offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := pmq.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (pmq *PhotosMetadataQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(pmq.driver.Dialect())
	t1 := builder.Table(photosmetadata.Table)
	columns := pmq.fields
	if len(columns) == 0 {
		columns = photosmetadata.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if pmq.sql != nil {
		selector = pmq.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if pmq.unique != nil && *pmq.unique {
		selector.Distinct()
	}
	for _, p := range pmq.predicates {
		p(selector)
	}
	for _, p := range pmq.order {
		p(selector)
	}
	if offset := pmq.offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := pmq.limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PhotosMetadataGroupBy is the group-by builder for PhotosMetadata entities.
type PhotosMetadataGroupBy struct {
	config
	fields []string
	fns    []AggregateFunc
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Aggregate adds the given aggregation functions to the group-by query.
func (pmgb *PhotosMetadataGroupBy) Aggregate(fns ...AggregateFunc) *PhotosMetadataGroupBy {
	pmgb.fns = append(pmgb.fns, fns...)
	return pmgb
}

// Scan applies the group-by query and scans the result into the given value.
func (pmgb *PhotosMetadataGroupBy) Scan(ctx context.Context, v interface{}) error {
	query, err := pmgb.path(ctx)
	if err != nil {
		return err
	}
	pmgb.sql = query
	return pmgb.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) ScanX(ctx context.Context, v interface{}) {
	if err := pmgb.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Strings(ctx context.Context) ([]string, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataGroupBy.Strings is not achievable when grouping more than 1 field")
	}
	var v []string
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) StringsX(ctx context.Context) []string {
	v, err := pmgb.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pmgb.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataGroupBy.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) StringX(ctx context.Context) string {
	v, err := pmgb.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Ints(ctx context.Context) ([]int, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataGroupBy.Ints is not achievable when grouping more than 1 field")
	}
	var v []int
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) IntsX(ctx context.Context) []int {
	v, err := pmgb.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pmgb.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataGroupBy.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) IntX(ctx context.Context) int {
	v, err := pmgb.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Float64s(ctx context.Context) ([]float64, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataGroupBy.Float64s is not achievable when grouping more than 1 field")
	}
	var v []float64
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) Float64sX(ctx context.Context) []float64 {
	v, err := pmgb.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pmgb.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataGroupBy.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) Float64X(ctx context.Context) float64 {
	v, err := pmgb.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from group-by.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Bools(ctx context.Context) ([]bool, error) {
	if len(pmgb.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataGroupBy.Bools is not achievable when grouping more than 1 field")
	}
	var v []bool
	if err := pmgb.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) BoolsX(ctx context.Context) []bool {
	v, err := pmgb.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a group-by query.
// It is only allowed when executing a group-by query with one field.
func (pmgb *PhotosMetadataGroupBy) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pmgb.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataGroupBy.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pmgb *PhotosMetadataGroupBy) BoolX(ctx context.Context) bool {
	v, err := pmgb.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pmgb *PhotosMetadataGroupBy) sqlScan(ctx context.Context, v interface{}) error {
	for _, f := range pmgb.fields {
		if !photosmetadata.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("invalid field %q for group-by", f)}
		}
	}
	selector := pmgb.sqlQuery()
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := pmgb.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

func (pmgb *PhotosMetadataGroupBy) sqlQuery() *sql.Selector {
	selector := pmgb.sql.Select()
	aggregation := make([]string, 0, len(pmgb.fns))
	for _, fn := range pmgb.fns {
		aggregation = append(aggregation, fn(selector))
	}
	// If no columns were selected in a custom aggregation function, the default
	// selection is the fields used for "group-by", and the aggregation functions.
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(pmgb.fields)+len(pmgb.fns))
		for _, f := range pmgb.fields {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	return selector.GroupBy(selector.Columns(pmgb.fields...)...)
}

// PhotosMetadataSelect is the builder for selecting fields of PhotosMetadata entities.
type PhotosMetadataSelect struct {
	*PhotosMetadataQuery
	// intermediate query (i.e. traversal path).
	sql *sql.Selector
}

// Scan applies the selector query and scans the result into the given value.
func (pms *PhotosMetadataSelect) Scan(ctx context.Context, v interface{}) error {
	if err := pms.prepareQuery(ctx); err != nil {
		return err
	}
	pms.sql = pms.PhotosMetadataQuery.sqlQuery(ctx)
	return pms.sqlScan(ctx, v)
}

// ScanX is like Scan, but panics if an error occurs.
func (pms *PhotosMetadataSelect) ScanX(ctx context.Context, v interface{}) {
	if err := pms.Scan(ctx, v); err != nil {
		panic(err)
	}
}

// Strings returns list of strings from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Strings(ctx context.Context) ([]string, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataSelect.Strings is not achievable when selecting more than 1 field")
	}
	var v []string
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// StringsX is like Strings, but panics if an error occurs.
func (pms *PhotosMetadataSelect) StringsX(ctx context.Context) []string {
	v, err := pms.Strings(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// String returns a single string from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) String(ctx context.Context) (_ string, err error) {
	var v []string
	if v, err = pms.Strings(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataSelect.Strings returned %d results when one was expected", len(v))
	}
	return
}

// StringX is like String, but panics if an error occurs.
func (pms *PhotosMetadataSelect) StringX(ctx context.Context) string {
	v, err := pms.String(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Ints returns list of ints from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Ints(ctx context.Context) ([]int, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataSelect.Ints is not achievable when selecting more than 1 field")
	}
	var v []int
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// IntsX is like Ints, but panics if an error occurs.
func (pms *PhotosMetadataSelect) IntsX(ctx context.Context) []int {
	v, err := pms.Ints(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Int returns a single int from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Int(ctx context.Context) (_ int, err error) {
	var v []int
	if v, err = pms.Ints(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataSelect.Ints returned %d results when one was expected", len(v))
	}
	return
}

// IntX is like Int, but panics if an error occurs.
func (pms *PhotosMetadataSelect) IntX(ctx context.Context) int {
	v, err := pms.Int(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64s returns list of float64s from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Float64s(ctx context.Context) ([]float64, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataSelect.Float64s is not achievable when selecting more than 1 field")
	}
	var v []float64
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// Float64sX is like Float64s, but panics if an error occurs.
func (pms *PhotosMetadataSelect) Float64sX(ctx context.Context) []float64 {
	v, err := pms.Float64s(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Float64 returns a single float64 from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Float64(ctx context.Context) (_ float64, err error) {
	var v []float64
	if v, err = pms.Float64s(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataSelect.Float64s returned %d results when one was expected", len(v))
	}
	return
}

// Float64X is like Float64, but panics if an error occurs.
func (pms *PhotosMetadataSelect) Float64X(ctx context.Context) float64 {
	v, err := pms.Float64(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bools returns list of bools from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Bools(ctx context.Context) ([]bool, error) {
	if len(pms.fields) > 1 {
		return nil, errors.New("ent: PhotosMetadataSelect.Bools is not achievable when selecting more than 1 field")
	}
	var v []bool
	if err := pms.Scan(ctx, &v); err != nil {
		return nil, err
	}
	return v, nil
}

// BoolsX is like Bools, but panics if an error occurs.
func (pms *PhotosMetadataSelect) BoolsX(ctx context.Context) []bool {
	v, err := pms.Bools(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Bool returns a single bool from a selector. It is only allowed when selecting one field.
func (pms *PhotosMetadataSelect) Bool(ctx context.Context) (_ bool, err error) {
	var v []bool
	if v, err = pms.Bools(ctx); err != nil {
		return
	}
	switch len(v) {
	case 1:
		return v[0], nil
	case 0:
		err = &NotFoundError{photosmetadata.Label}
	default:
		err = fmt.Errorf("ent: PhotosMetadataSelect.Bools returned %d results when one was expected", len(v))
	}
	return
}

// BoolX is like Bool, but panics if an error occurs.
func (pms *PhotosMetadataSelect) BoolX(ctx context.Context) bool {
	v, err := pms.Bool(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

func (pms *PhotosMetadataSelect) sqlScan(ctx context.Context, v interface{}) error {
	rows := &sql.Rows{}
	query, args := pms.sql.Query()
	if err := pms.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
