// Code generated by entc, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// PhotosMetadata is the predicate function for photosmetadata builders.
type PhotosMetadata func(*sql.Selector)

// Profile is the predicate function for profile builders.
type Profile func(*sql.Selector)
